-- GENERATED by db/seed/generate.py — do not edit by hand.

BEGIN;

INSERT INTO item (slug, name, unit, aisle, kcal_per_100, protein_per_100,
                  carb_per_100, fat_per_100, keeps, shelf_life_days, category) VALUES
  ('pasta', 'Penne pasta', 'g', 'Pasta & rice', 352, 12.0, NULL, NULL, 'staple', NULL, 'carb'),
  ('rice', 'Long grain rice', 'g', 'Pasta & rice', 349, 7.0, NULL, NULL, 'staple', NULL, 'carb'),
  ('noodles', 'Egg noodles', 'g', 'Pasta & rice', 360, 12.0, NULL, NULL, 'staple', NULL, 'carb'),
  ('oats', 'Porridge oats', 'g', 'Cereals', 356, 11.0, NULL, NULL, 'staple', NULL, 'carb'),
  ('bread', 'Wholemeal loaf', 'g', 'Bakery', 236, 9.5, NULL, NULL, 'perishable', 5, 'carb'),
  ('potato', 'White potatoes', 'g', 'Fresh produce', 77, 2.0, NULL, NULL, 'perishable', 21, 'carb'),
  ('tortilla', 'Tortilla wraps x8', 'g', 'Bakery', 300, 8.5, NULL, NULL, 'perishable', 14, 'carb'),
  ('chicken', 'Chicken thigh fillets', 'g', 'Meat & fish', 177, 19.0, NULL, NULL, 'perishable', 3, 'protein'),
  ('mince', 'Beef mince 20%', 'g', 'Meat & fish', 250, 18.0, NULL, NULL, 'perishable', 3, 'protein'),
  ('eggs', 'Eggs (large)', 'unit', 'Dairy & eggs', 78, 6.5, NULL, NULL, 'perishable', 21, 'protein'),
  ('tuna', 'Tuna chunks 145g', 'g', 'Tins', 99, 23.5, NULL, NULL, 'staple', NULL, 'protein'),
  ('lentils', 'Red split lentils', 'g', 'Tins & pulses', 352, 24.0, NULL, NULL, 'staple', NULL, 'protein'),
  ('chickpeas', 'Chickpeas 400g tin', 'g', 'Tins & pulses', 115, 7.0, NULL, NULL, 'staple', NULL, 'protein'),
  ('kidney', 'Kidney beans 400g', 'g', 'Tins & pulses', 100, 6.9, NULL, NULL, 'staple', NULL, 'protein'),
  ('beans', 'Baked beans 410g', 'g', 'Tins & pulses', 82, 4.7, NULL, NULL, 'staple', NULL, 'protein'),
  ('cheese', 'Mature cheddar', 'g', 'Dairy & eggs', 416, 25.0, NULL, NULL, 'perishable', 21, 'dairy'),
  ('pb', 'Peanut butter', 'g', 'Spreads', 600, 25.0, NULL, NULL, 'staple', NULL, 'protein'),
  ('milk', 'Semi-skimmed milk', 'ml', 'Dairy & eggs', 50, 3.6, NULL, NULL, 'perishable', 7, 'dairy'),
  ('yoghurt', 'Natural yoghurt 1kg', 'g', 'Dairy & eggs', 60, 5.5, NULL, NULL, 'perishable', 10, 'dairy'),
  ('toms', 'Chopped tomatoes', 'g', 'Tins', 20, 1.2, NULL, NULL, 'staple', NULL, 'veg'),
  ('onion', 'Brown onions', 'g', 'Fresh produce', 40, 1.1, NULL, NULL, 'perishable', 30, 'veg'),
  ('carrot', 'Carrots', 'g', 'Fresh produce', 41, 0.9, NULL, NULL, 'perishable', 14, 'veg'),
  ('frozveg', 'Frozen mixed veg', 'g', 'Frozen', 45, 2.8, NULL, NULL, 'staple', NULL, 'veg'),
  ('peas', 'Frozen peas', 'g', 'Frozen', 77, 5.4, NULL, NULL, 'staple', NULL, 'veg'),
  ('banana', 'Bananas (each)', 'unit', 'Fresh produce', 95, 1.2, NULL, NULL, 'perishable', 5, 'veg'),
  ('oil', 'Vegetable oil 1L', 'ml', 'Cooking', 884, 0.0, NULL, NULL, 'staple', NULL, 'flavour'),
  ('curry', 'Curry powder', 'g', 'Cooking', 325, 12.0, NULL, NULL, 'staple', NULL, 'flavour'),
  ('stock', 'Stock cubes x10', 'unit', 'Cooking', 20, 1.0, NULL, NULL, 'staple', NULL, 'flavour');

COMMIT;
