-- GENERATED by db/seed/generate.py — do not edit by hand.

BEGIN;

INSERT INTO item_price (item_id, store_id, pack_size, price, source,
                        observed_at, is_current)
SELECT i.id, s.id, v.pack_size, v.price, 'seed', '2026-08-31T00:00:00Z'::timestamptz, true
FROM (VALUES
  ('pasta', 'aldi', 500::numeric, 0.45::numeric),
  ('pasta', 'tesco', 500::numeric, 0.55::numeric),
  ('rice', 'aldi', 1000::numeric, 0.75::numeric),
  ('rice', 'tesco', 1000::numeric, 0.9::numeric),
  ('noodles', 'aldi', 375::numeric, 0.75::numeric),
  ('noodles', 'tesco', 375::numeric, 0.9::numeric),
  ('oats', 'aldi', 1000::numeric, 0.9::numeric),
  ('oats', 'tesco', 1000::numeric, 1.15::numeric),
  ('bread', 'aldi', 800::numeric, 0.75::numeric),
  ('bread', 'tesco', 800::numeric, 0.95::numeric),
  ('potato', 'aldi', 2500::numeric, 1.65::numeric),
  ('potato', 'tesco', 2500::numeric, 1.95::numeric),
  ('tortilla', 'aldi', 448::numeric, 0.85::numeric),
  ('tortilla', 'tesco', 448::numeric, 1.1::numeric),
  ('chicken', 'aldi', 650::numeric, 3.29::numeric),
  ('chicken', 'tesco', 650::numeric, 3.95::numeric),
  ('mince', 'aldi', 500::numeric, 2.79::numeric),
  ('mince', 'tesco', 500::numeric, 3.35::numeric),
  ('eggs', 'aldi', 15::numeric, 1.99::numeric),
  ('eggs', 'tesco', 15::numeric, 2.45::numeric),
  ('tuna', 'aldi', 145::numeric, 0.85::numeric),
  ('tuna', 'tesco', 145::numeric, 1.05::numeric),
  ('lentils', 'aldi', 500::numeric, 0.99::numeric),
  ('lentils', 'tesco', 500::numeric, 1.25::numeric),
  ('chickpeas', 'aldi', 400::numeric, 0.39::numeric),
  ('chickpeas', 'tesco', 400::numeric, 0.49::numeric),
  ('kidney', 'aldi', 400::numeric, 0.39::numeric),
  ('kidney', 'tesco', 400::numeric, 0.49::numeric),
  ('beans', 'aldi', 410::numeric, 0.35::numeric),
  ('beans', 'tesco', 410::numeric, 0.45::numeric),
  ('cheese', 'aldi', 400::numeric, 2.69::numeric),
  ('cheese', 'tesco', 400::numeric, 3.25::numeric),
  ('pb', 'aldi', 340::numeric, 1.39::numeric),
  ('pb', 'tesco', 340::numeric, 1.7::numeric),
  ('milk', 'aldi', 2272::numeric, 1.45::numeric),
  ('milk', 'tesco', 2272::numeric, 1.55::numeric),
  ('yoghurt', 'aldi', 1000::numeric, 1.15::numeric),
  ('yoghurt', 'tesco', 1000::numeric, 1.4::numeric),
  ('toms', 'aldi', 400::numeric, 0.39::numeric),
  ('toms', 'tesco', 400::numeric, 0.47::numeric),
  ('onion', 'aldi', 1000::numeric, 0.95::numeric),
  ('onion', 'tesco', 1000::numeric, 1.15::numeric),
  ('carrot', 'aldi', 1000::numeric, 0.55::numeric),
  ('carrot', 'tesco', 1000::numeric, 0.7::numeric),
  ('frozveg', 'aldi', 1000::numeric, 1.29::numeric),
  ('frozveg', 'tesco', 1000::numeric, 1.5::numeric),
  ('peas', 'aldi', 900::numeric, 1.09::numeric),
  ('peas', 'tesco', 900::numeric, 1.3::numeric),
  ('banana', 'aldi', 5::numeric, 0.79::numeric),
  ('banana', 'tesco', 5::numeric, 0.95::numeric),
  ('oil', 'aldi', 1000::numeric, 1.85::numeric),
  ('oil', 'tesco', 1000::numeric, 2.15::numeric),
  ('curry', 'aldi', 100::numeric, 0.79::numeric),
  ('curry', 'tesco', 100::numeric, 0.95::numeric),
  ('stock', 'aldi', 10::numeric, 0.55::numeric),
  ('stock', 'tesco', 10::numeric, 0.7::numeric)
) AS v(item_slug, store_slug, pack_size, price)
JOIN item  i ON i.slug  = v.item_slug
JOIN store s ON s.slug = v.store_slug;

COMMIT;
