-- GENERATED by db/seed/generate.py (extra_recipes.py) — do not edit by hand.

BEGIN;

INSERT INTO recipe (slug, name, minutes, meal_slot, method_md, serves_base) VALUES
  ('pbtoast', 'Peanut butter toast & banana', 5, 'breakfast', NULL, 1),
  ('beanstoast', 'Beans on toast with cheese', 10, 'breakfast', NULL, 1),
  ('eggwrap', 'Egg & cheese breakfast wrap', 10, 'breakfast', NULL, 1),
  ('oatpancake', 'Oat pancakes with yoghurt', 15, 'breakfast', NULL, 1);


INSERT INTO recipe_ingredient (recipe_id, item_id, qty_per_serving, optional)
SELECT r.id, i.id, v.qty, false
FROM (VALUES
  ('pbtoast', 'bread', 90::numeric),
  ('pbtoast', 'pb', 30::numeric),
  ('pbtoast', 'banana', 1::numeric),
  ('beanstoast', 'beans', 205::numeric),
  ('beanstoast', 'bread', 90::numeric),
  ('beanstoast', 'cheese', 25::numeric),
  ('eggwrap', 'eggs', 2::numeric),
  ('eggwrap', 'tortilla', 112::numeric),
  ('eggwrap', 'cheese', 25::numeric),
  ('eggwrap', 'oil', 6::numeric),
  ('oatpancake', 'oats', 90::numeric),
  ('oatpancake', 'eggs', 1::numeric),
  ('oatpancake', 'milk', 120::numeric),
  ('oatpancake', 'yoghurt', 100::numeric),
  ('oatpancake', 'oil', 6::numeric)
) AS v(recipe_slug, item_slug, qty)
JOIN recipe r ON r.slug = v.recipe_slug
JOIN item i ON i.slug = v.item_slug;


INSERT INTO recipe_tag (recipe_id, tag)
SELECT r.id, v.tag FROM (VALUES
  ('pbtoast', 'vegetarian'),
  ('pbtoast', 'no-oven'),
  ('beanstoast', 'vegetarian'),
  ('beanstoast', 'no-oven'),
  ('eggwrap', 'vegetarian'),
  ('eggwrap', 'no-oven'),
  ('oatpancake', 'vegetarian'),
  ('oatpancake', 'no-oven')
) AS v(recipe_slug, tag)
JOIN recipe r ON r.slug = v.recipe_slug;

COMMIT;
