-- GENERATED by services/solver/scripts/generate_methods.py
-- Cooking copy written by Claude, validated by app.method_check:
-- no quantities, no ingredient outside each recipe's own list.
-- CLAUDE.md rule 1 — copy only; selection, pricing and quantities
-- remain the solver's.

BEGIN;

UPDATE recipe SET method_md = 'Baked beans on toast under a blanket of melted cheddar.

1. Warm the baked beans in a small pan over a medium heat.
2. Toast the bread until golden.
3. Grate the cheddar over the hot toast.
4. Spoon the beans on top and grill briefly until the cheese melts.' WHERE slug = 'beanstoast';
UPDATE recipe SET method_md = 'A rich lentil bolognese, slow-simmered and stirred through pasta.

1. Heat the oil in a large pan and soften the onion and carrot.
2. Add the lentils, tomatoes and stock, then bring to a simmer.
3. Cook gently for 25 minutes, stirring now and then, until the lentils collapse.
4. Boil the pasta in salted water until just tender.
5. Drain the pasta and stir it through the sauce.' WHERE slug = 'bolognese';
UPDATE recipe SET method_md = 'A quick chickpea curry with tomatoes, served over rice.

1. Heat the oil and soften the onion over a medium heat.
2. Stir in the curry powder and cook for a minute until fragrant.
3. Add the chickpeas and tomatoes, then simmer for 15 minutes.
4. Boil the rice and serve the curry over it.' WHERE slug = 'chickcurry';
UPDATE recipe SET method_md = 'A proper beef chilli, simmered until thick, with rice.

1. Heat the oil in a heavy pan and soften the onion.
2. Turn up the heat and brown the mince, breaking it up as it cooks.
3. Add the tomatoes, kidney beans and stock.
4. Simmer uncovered for 25 minutes until thick.
5. Boil the rice and serve alongside.' WHERE slug = 'chilli';
UPDATE recipe SET method_md = 'A thick, gently spiced red lentil dahl served with rice.

1. Heat the oil in a pan and soften the onion.
2. Stir in the curry powder and let it toast for a minute.
3. Add the lentils, tomatoes and stock, then simmer for 20 minutes until thick.
4. Season with salt and boil the rice.
5. Serve the dahl over the rice.' WHERE slug = 'dahl';
UPDATE recipe SET method_md = 'Soft, slow-scrambled eggs piled onto hot toast.

1. Beat the eggs with the milk and a pinch of salt.
2. Heat the oil in a non-stick pan over a low heat.
3. Pour in the eggs and stir gently until only just set.
4. Take the pan off the heat, toast the bread and pile the eggs on top.' WHERE slug = 'eggstoast';
UPDATE recipe SET method_md = 'A hot breakfast wrap with soft egg and melted cheddar.

1. Beat the eggs and season with salt and pepper.
2. Heat the oil in a pan and cook the eggs until just set.
3. Warm the tortilla in a dry pan for a few seconds each side.
4. Scatter the cheddar over the tortilla, add the egg and roll it up tightly.' WHERE slug = 'eggwrap';
UPDATE recipe SET method_md = 'Egg fried rice with peas, best made with rice cooked the day before.

1. Cook the rice and let it cool, or use rice from the fridge.
2. Heat the oil in a wide pan and fry the onion until soft.
3. Push the onion aside, pour in the beaten eggs and scramble them quickly.
4. Add the rice and peas and stir-fry over a high heat until piping hot.' WHERE slug = 'friedrice';
UPDATE recipe SET method_md = 'Baked potato with baked beans and melted cheddar.

1. Heat the oven to 200C.
2. Prick the potatoes, rub them with salt and bake for about an hour until crisp outside and soft within.
3. Warm the baked beans in a pan towards the end.
4. Split the potatoes, spoon the beans in and grate the cheddar over.' WHERE slug = 'jacket';
UPDATE recipe SET method_md = 'Thick oat pancakes topped with cool yoghurt.

1. Stir the oats, milk and eggs together into a thick batter.
2. Leave the batter to stand while the pan heats.
3. Heat a little of the oil in a frying pan and spoon in the batter to make small rounds.
4. Cook until bubbles appear on top, then flip and cook the other side.
5. Serve warm with the yoghurt spooned over.' WHERE slug = 'oatpancake';
UPDATE recipe SET method_md = 'A folded cheese omelette with toast on the side.

1. Beat the eggs with salt and pepper.
2. Heat the oil in a small non-stick pan over a medium heat.
3. Pour in the eggs and draw the setting edges into the middle.
4. Scatter the cheddar over one half, fold, and slide onto the plate.
5. Toast the bread and serve alongside.' WHERE slug = 'omelette';
UPDATE recipe SET method_md = 'Peanut butter on toast with sliced banana, start to finish in minutes.

1. Toast the bread to your liking.
2. Spread the peanut butter over while the toast is still hot so it softens.
3. Slice the banana and lay it over the top.' WHERE slug = 'pbtoast';
UPDATE recipe SET method_md = 'Creamy oat porridge with banana and a swirl of peanut butter.

1. Put the oats and milk in a pan over a medium heat.
2. Stir often and cook until thick and creamy.
3. Slice the banana into the bowl.
4. Swirl the peanut butter through just before eating.' WHERE slug = 'porridge';
UPDATE recipe SET method_md = 'A thick carrot and lentil soup, with bread for dunking.

1. Heat the oil in a large pan and soften the onion.
2. Add the carrots and cook for a few minutes.
3. Stir in the lentils and stock, then simmer for 25 minutes until everything is soft.
4. Blend until smooth and season with salt and pepper.
5. Serve with the bread.' WHERE slug = 'soup';
UPDATE recipe SET method_md = 'A fast chicken and noodle stir-fry with plenty of vegetables.

1. Slice the chicken into strips.
2. Heat the oil in a wok or large pan until very hot.
3. Stir-fry the chicken until cooked through and no longer pink in the middle.
4. Add the frozen veg and cook until hot.
5. Boil the noodles, drain and toss them through.' WHERE slug = 'stirfry';
UPDATE recipe SET method_md = 'Chicken and vegetables roasted on one tray, served with rice.

1. Heat the oven to 200C.
2. Toss the chicken and frozen veg with the oil on a large tray.
3. Roast for 35 minutes, turning once, until the chicken is cooked through.
4. Boil the rice with the stock stirred into the water.
5. Serve the tray straight over the rice.' WHERE slug = 'traybake';
UPDATE recipe SET method_md = 'A baked tuna pasta with tomato sauce and a cheese crust.

1. Heat the oven to 190C.
2. Boil the pasta in salted water until just short of tender, then drain.
3. Cook the onion in a dry pan for a minute, then add the tomatoes and simmer for ten minutes.
4. Flake the tuna through the sauce and stir the pasta in.
5. Tip into a dish, grate the cheddar over and bake for 15 minutes until bubbling.' WHERE slug = 'tunapasta';
UPDATE recipe SET method_md = 'A cold chicken wrap with grated carrot and a yoghurt dressing.

1. Grill the chicken until cooked through, then slice it and let it cool.
2. Grate the carrot into a bowl.
3. Loosen the yoghurt with a little water and season it with salt and pepper.
4. Lay the chicken and carrot along the middle of the tortilla.
5. Spoon the dressing over and roll it up tightly.' WHERE slug = 'wrap';
UPDATE recipe SET method_md = 'A no-cook breakfast bowl of yoghurt, oats and peanut butter.

1. Spoon the yoghurt into a bowl.
2. Stir the oats through so they soften slightly.
3. Slice the banana over the top.
4. Finish with the peanut butter.' WHERE slug = 'yogpb';

COMMIT;
