-- GENERATED by db/seed/generate.py (snack_recipes.py) — do not edit by hand.

BEGIN;

INSERT INTO recipe (slug, name, minutes, meal_slot, method_md, serves_base) VALUES
  ('pbbanana', 'Peanut butter banana', 2, 'snack', NULL, 1),
  ('cheesetoast', 'Cheese on toast', 6, 'snack', NULL, 1),
  ('oatpb', 'Oats, peanut butter & banana pot', 3, 'snack', NULL, 1),
  ('yogbanana', 'Yoghurt with oats and banana', 3, 'snack', NULL, 1),
  ('boiledeggs', 'Boiled eggs', 10, 'snack', NULL, 1);


INSERT INTO recipe_ingredient (recipe_id, item_id, qty_per_serving, optional)
SELECT r.id, i.id, v.qty, false
FROM (VALUES
  ('pbbanana', 'pb', 40::numeric),
  ('pbbanana', 'banana', 1::numeric),
  ('cheesetoast', 'bread', 80::numeric),
  ('cheesetoast', 'cheese', 40::numeric),
  ('oatpb', 'oats', 60::numeric),
  ('oatpb', 'pb', 30::numeric),
  ('oatpb', 'banana', 1::numeric),
  ('yogbanana', 'yoghurt', 150::numeric),
  ('yogbanana', 'oats', 40::numeric),
  ('yogbanana', 'banana', 1::numeric),
  ('boiledeggs', 'eggs', 2::numeric),
  ('boiledeggs', 'bread', 40::numeric)
) AS v(recipe_slug, item_slug, qty)
JOIN recipe r ON r.slug=v.recipe_slug
JOIN item i ON i.slug=v.item_slug;


INSERT INTO recipe_tag (recipe_id, tag)
SELECT r.id, v.tag FROM (VALUES
  ('pbbanana', 'vegetarian'),
  ('pbbanana', 'no-oven'),
  ('cheesetoast', 'vegetarian'),
  ('cheesetoast', 'no-oven'),
  ('oatpb', 'vegetarian'),
  ('oatpb', 'no-oven'),
  ('yogbanana', 'vegetarian'),
  ('yogbanana', 'no-oven'),
  ('boiledeggs', 'vegetarian'),
  ('boiledeggs', 'no-oven')
) AS v(recipe_slug, tag)
JOIN recipe r ON r.slug=v.recipe_slug;

COMMIT;
