-- GENERATED by services/solver/scripts/generate_methods.py
-- Snack copy, validated by app.method_check: no quantities, no ingredient
-- outside each recipe's own list.

BEGIN;

UPDATE recipe SET method_md = 'Boiled eggs with toast soldiers.

1. Lower the eggs into boiling water.
2. Cook for seven minutes for a soft centre, ten for firm.
3. Toast the bread and cut it into strips.
4. Season with salt and pepper and eat straight away.' WHERE slug = 'boiledeggs';
UPDATE recipe SET method_md = 'Grilled cheese on toast, the fastest hot snack there is.

1. Heat the grill.
2. Toast the bread lightly on one side.
3. Grate the cheddar over the untoasted side.
4. Grill until the cheese bubbles and starts to colour.' WHERE slug = 'cheesetoast';
UPDATE recipe SET method_md = 'A thick oat pot with peanut butter and banana, no cooking needed.

1. Stir the oats with a splash of water and leave them to soften.
2. Slice the banana over the top.
3. Swirl the peanut butter through and eat.' WHERE slug = 'oatpb';
UPDATE recipe SET method_md = 'Peanut butter and banana, assembled in about a minute.

1. Slice the banana.
2. Spread the peanut butter over the slices, or dip them straight in.
3. Eat immediately, before the banana browns.' WHERE slug = 'pbbanana';
UPDATE recipe SET method_md = 'Yoghurt with oats and banana, spooned together cold.

1. Spoon the yoghurt into a bowl.
2. Stir the oats through so they soften.
3. Slice the banana over the top.' WHERE slug = 'yogbanana';

COMMIT;
