"""
Generate seed migrations from prototype/catalogue.py.

Run:  python3 db/seed/generate.py

The catalogue is ported by machine, not retyped, so prices and macros cannot
drift from the prototype. The only hand-authored input is classify.py.
Output is committed — the migrations, not this script, are what runs.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path[:0] = [HERE, os.path.join(ROOT, "prototype")]

from catalogue import ITEMS, RECIPES, serving_macros          # noqa: E402
from classify import CLASSIFICATION, NEEDS_OVEN, MEAT_FISH    # noqa: E402

OUT = os.path.join(ROOT, "db", "migrations")
STORES = [("aldi", "Aldi"), ("tesco", "Tesco")]

# Seed prices came from the prototype with no recorded observation date. We do
# not invent one: source='seed' is what the confidence UI must key off, and a
# 'seed' price is "unverified" no matter how recent its timestamp looks.
SEED_OBSERVED_AT = "2026-08-31T00:00:00Z"

BANNER = "-- GENERATED by db/seed/generate.py — do not edit by hand.\n"


def q(s):
    return "'" + str(s).replace("'", "''") + "'"


def nn(v):
    return "NULL" if v is None else str(v)


def main():
    assert set(ITEMS) == set(CLASSIFICATION), "classify.py is out of sync with catalogue.py"

    # 002 — stores -------------------------------------------------------
    lines = [BANNER, "BEGIN;\n", "INSERT INTO store (slug, name, country) VALUES"]
    lines.append(",\n".join(f"  ({q(s)}, {q(n)}, 'GB')" for s, n in STORES) + ";\n")
    lines.append("COMMIT;\n")
    write("002_seed_stores.sql", lines)

    # 003 — items --------------------------------------------------------
    lines = [BANNER, "BEGIN;\n",
             "INSERT INTO item (slug, name, unit, aisle, kcal_per_100, protein_per_100,\n"
             "                  carb_per_100, fat_per_100, keeps, shelf_life_days, category) VALUES"]
    rows = []
    for slug, it in ITEMS.items():
        keeps, shelf, cat = CLASSIFICATION[slug]
        rows.append(
            f"  ({q(slug)}, {q(it['name'])}, {q(it['unit'])}, {q(it['aisle'])}, "
            f"{it['kcal']}, {it['protein']}, NULL, NULL, "
            f"{q(keeps)}, {nn(shelf)}, {q(cat)})"
        )
    lines.append(",\n".join(rows) + ";\n")
    lines.append("COMMIT;\n")
    write("003_seed_items.sql", lines)

    # 004 — prices -------------------------------------------------------
    lines = [BANNER, "BEGIN;\n",
             "INSERT INTO item_price (item_id, store_id, pack_size, price, source,\n"
             "                        observed_at, is_current)\n"
             "SELECT i.id, s.id, v.pack_size, v.price, 'seed', "
             f"{q(SEED_OBSERVED_AT)}::timestamptz, true\n"
             "FROM (VALUES"]
    rows = []
    for slug, it in ITEMS.items():
        for store, _ in STORES:
            rows.append(f"  ({q(slug)}, {q(store)}, {it['pack']}::numeric, {it[store]}::numeric)")
    lines.append(",\n".join(rows))
    lines.append(") AS v(item_slug, store_slug, pack_size, price)\n"
                 "JOIN item  i ON i.slug  = v.item_slug\n"
                 "JOIN store s ON s.slug = v.store_slug;\n")
    lines.append("COMMIT;\n")
    write("004_seed_prices.sql", lines)

    # 005 — recipes ------------------------------------------------------
    lines = [BANNER, "BEGIN;\n",
             "INSERT INTO recipe (slug, name, minutes, meal_slot, method_md, serves_base) VALUES"]
    rows = []
    for slug, r in RECIPES.items():
        slot = "breakfast" if r.get("meal") == "breakfast" else "main"
        # method_md is NULL: the prototype has no cooking steps. Catalogue gap.
        rows.append(f"  ({q(slug)}, {q(r['name'])}, {r['mins']}, {q(slot)}, NULL, 1)")
    lines.append(",\n".join(rows) + ";\n")

    lines.append("\nINSERT INTO recipe_ingredient (recipe_id, item_id, qty_per_serving, optional)\n"
                 "SELECT r.id, i.id, v.qty, false\n"
                 "FROM (VALUES")
    rows = []
    for slug, r in RECIPES.items():
        for iid, qty in r["ing"].items():
            rows.append(f"  ({q(slug)}, {q(iid)}, {qty}::numeric)")
    lines.append(",\n".join(rows))
    lines.append(") AS v(recipe_slug, item_slug, qty)\n"
                 "JOIN recipe r ON r.slug = v.recipe_slug\n"
                 "JOIN item   i ON i.slug = v.item_slug;\n")

    # Tags: vegetarian and no-oven are derived from data. 'one-pot' is NOT
    # emitted — it cannot be derived without method text, and guessing it would
    # be inventing data. Logged as a catalogue gap.
    lines.append("\nINSERT INTO recipe_tag (recipe_id, tag)\n"
                 "SELECT r.id, v.tag FROM (VALUES")
    rows = []
    for slug, r in RECIPES.items():
        if not (set(r["ing"]) & MEAT_FISH):
            rows.append(f"  ({q(slug)}, 'vegetarian')")
        if slug not in NEEDS_OVEN:
            rows.append(f"  ({q(slug)}, 'no-oven')")
    lines.append(",\n".join(rows))
    lines.append(") AS v(recipe_slug, tag)\nJOIN recipe r ON r.slug = v.recipe_slug;\n")
    lines.append("COMMIT;\n")
    write("005_seed_recipes.sql", lines)

    report()


def write(name, lines):
    path = os.path.join(OUT, name)
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"  wrote {name}")


def report():
    print(f"\nitems {len(ITEMS)} · prices {len(ITEMS) * len(STORES)} · recipes {len(RECIPES)} "
          f"· ingredient rows {sum(len(r['ing']) for r in RECIPES.values())}")
    staple = [s for s, (k, _, _) in CLASSIFICATION.items() if k == "staple"]
    print(f"staple {len(staple)} · perishable {len(ITEMS) - len(staple)}")
    print("\nrecipe macros per serving (sanity check against prototype):")
    for slug in RECIPES:
        kcal, protein = serving_macros(slug)
        print(f"  {slug:<12} {kcal:>7.0f} kcal  {protein:>6.1f}g protein")


if __name__ == "__main__":
    main()
